DOCKER_COMPOSE=docker-compose
DOCKER_COMPOSE_FILE=docker-compose.yml
DOCKER_COMPOSE_FILE_DEVELOPMENT=docker-compose.development.yml
DOCKER_COMPOSE_UP=up
DOCKER_COMPOSE_DETACH=-d
DOCKER_COMPOSE_BUILD=--build

dev:
	$(DOCKER_COMPOSE) -f ${DOCKER_COMPOSE_FILE} -f ${DOCKER_COMPOSE_FILE_DEVELOPMENT} ${DOCKER_COMPOSE_UP} ${DOCKER_COMPOSE_BUILD}

prod:
	$(DOCKER_COMPOSE) ${DOCKER_COMPOSE_UP} ${DOCKER_COMPOSE_BUILD}

down:
	$(DOCKER_COMPOSE) down
